// _table.js

const columns = [
  {
    key: 'id',
    label: 'S.No',
    _props: { scope: 'col' },
  },
  {
    key: 'Photo',
    label: 'Photo Profile',
    _props: { scope: 'col' },
  },
  {
    key: 'First_Name',
    label: 'First Name',
    _props: { scope: 'col' },
  },
  {
    key: 'Last_Name',
    label: 'First Name',
    _props: { scope: 'col' },
  },

  {
    key: 'Email',
    label: 'Email',
    _props: { scope: 'col' },
  },
  {
    key: 'Mobile',
    label: 'Mobile',
    _props: { scope: 'col' },
  },

  {
    key: 'Action',
    label: 'Actions',
    _props: { scope: 'col' },
  },
];


const items = [
  {
    id: 1,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'John',
    Last_Name: 'Doe',
    Email: 'john.doe@example.com',
    Mobile: '+1234567890',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 2,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Jane',
    Last_Name: 'Smith',
    Email: 'jane.smith@example.com',
    Mobile: '+9876543210',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 3,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Michael',
    Last_Name: 'Johnson',
    Email: 'michael.johnson@example.com',
    Mobile: '+1112223333',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 4,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Emily',
    Last_Name: 'Brown',
    Email: 'emily.brown@example.com',
    Mobile: '+4445556666',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 5,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'William',
    Last_Name: 'Davis',
    Email: 'william.davis@example.com',
    Mobile: '+7778889999',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 6,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Sophia',
    Last_Name: 'Martinez',
    Email: 'sophia.martinez@example.com',
    Mobile: '+2223334444',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 7,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Ethan',
    Last_Name: 'Garcia',
    Email: 'ethan.garcia@example.com',
    Mobile: '+5556667777',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 8,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Olivia',
    Last_Name: 'Lopez',
    Email: 'olivia.lopez@example.com',
    Mobile: '+8889990000',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 9,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'James',
    Last_Name: 'Wilson',
    Email: 'james.wilson@example.com',
    Mobile: '+3334445555',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 10,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Ava',
    Last_Name: 'Hernandez',
    Email: 'ava.hernandez@example.com',
    Mobile: '+6667778888',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 11,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Alexander',
    Last_Name: 'King',
    Email: 'alexander.king@example.com',
    Mobile: '+1111111111',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 12,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Mia',
    Last_Name: 'Gonzalez',
    Email: 'mia.gonzalez@example.com',
    Mobile: '+4444444444',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 13,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Benjamin',
    Last_Name: 'Miller',
    Email: 'benjamin.miller@example.com',
    Mobile: '+7777777777',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 14,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Charlotte',
    Last_Name: 'Rodriguez',
    Email: 'charlotte.rodriguez@example.com',
    Mobile: '+2222222222',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 15,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Daniel',
    Last_Name: 'Lopez',
    Email: 'daniel.lopez@example.com',
    Mobile: '+5555555555',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 16,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Amelia',
    Last_Name: 'Martinez',
    Email: 'amelia.martinez@example.com',
    Mobile: '+8888888888',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 17,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Logan',
    Last_Name: 'Hernandez',
    Email: 'logan.hernandez@example.com',
    Mobile: '+3333333333',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 18,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Harper',
    Last_Name: 'Young',
    Email: 'harper.young@example.com',
    Mobile: '+6666666666',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 19,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Ryan',
    Last_Name: 'Allen',
    Email: 'ryan.allen@example.com',
    Mobile: '+9999999999',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 20,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Evelyn',
    Last_Name: 'Scott',
    Email: 'evelyn.scott@example.com',
    Mobile: '+1234567890',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 21,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Sebastian',
    Last_Name: 'King',
    Email: 'sebastian.king@example.com',
    Mobile: '+9876543210',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 22,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Isabella',
    Last_Name: 'Garcia',
    Email: 'isabella.garcia@example.com',
    Mobile: '+1112223333',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 23,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Elijah',
    Last_Name: 'Lopez',
    Email: 'elijah.lopez@example.com',
    Mobile: '+4445556666',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 24,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Avery',
    Last_Name: 'Martinez',
    Email: 'avery.martinez@example.com',
    Mobile: '+7778889999',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
  {
    id: 25,
    Photo: 'https://via.placeholder.com/50',
    First_Name: 'Grayson',
    Last_Name: 'Young',
    Email: 'grayson.young@example.com',
    Mobile: '+2223334444',
    Icons:['view','edit','delete'],
    _cellProps: { id: { scope: 'row' } },
  },
];

export { columns, items };
